DOCKER_IMAGE = docker-registry:5000/actiontech/compiler-centos7-gcc-9.4
CTN_NAME     = actiontech-compiler-centos7


override DOCKER_BIN = $(shell which docker)

build:
	$(DOCKER_BIN) build --network host -t $(DOCKER_IMAGE) .

push:
	$(DOCKER_BIN) push $(DOCKER_IMAGE)

run:
	$(DOCKER_BIN) run -t -d --privileged --name $(CTN_NAME) --volume $(PWD):/workbench --network host $(DOCKER_IMAGE)

stop:
	$(DOCKER_BIN) stop $(CTN_NAME) && $(DOCKER_BIN) rm $(CTN_NAME)

b: build run
	$(DOCKER_BIN) logs $(CTN_NAME)

